name: AWS OIDC Lab1

on:
  workflow_dispatch:

permissions:
  id-token: write # required for OIDC
  contents: read # required to checkout the repo

jobs:
  aws-lab-grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/githubconnect
        aws-region: us-east-1

    - name: Run Grading Tests
      run: |
        pip install pytest boto3
      
    - name: Run script
        run: python test_lab1.py